### ISSUE TITLE
Why only one current?

### ISSUE THREAD

**Issue by arj03** [ssbc/ssb-device-address#2]
My use case is: I have a pub with availability close to 1, but a laptop with lets say 10%. But I would like for people to know that they can reach me both through my pub but also my laptop if it is online. One could post two messages, but as I understand this, the idea is to only have 1 current?

**Comment by dominictarr** [comment]
oh, it's per device - so your pub is always online, and your laptop isn't. this (todo) will be linked with same-as, but at the connection level it's still treated as separate devices. your pub can be availabilty=1 and your laptop can be availability=0.1, and that's fine. Also note that unlike the old `pub` messages, you can't publish an address for someone else, only the feed you are actually posting from.

**Comment by arj03** [comment]
Ah yes, I see. Thanks! This is going to be excellent++
